modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="http://www.github.com/MelanX/botanical-machinery/issues/"
license="Apache 2.0"

[[mods]]
modId="botanicalmachinery"
version="${file.jarVersion}"
displayName="Botanical Machinery"
updateJSONURL="https://assets.melanx.de/updates/botanical-machinery.json"
displayURL="www.curseforge.com/members/melanx/"
authors="MelanX"
description='''
A Minecraft addon mod for Botania which makes automation easier.
'''

[[dependencies.botanicalmachinery]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.68,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.botanicalmachinery]]
    modId="libx"
    mandatory=true
    versionRange="[1.18.2-3.2.15,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.botanicalmachinery]]
    modId="botania"
    mandatory=true
    versionRange="[1.18.2-431,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.botanicalmachinery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
