modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="http://www.github.com/MelanX/botanical-machinery/issues/"

[[mods]]
modId="modid"
version="${file.jarVersion}"
displayName="Botanical Machinery"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/botanicalmachinery.json"
displayURL="www.curseforge.com/members/melanx/"
#logoFile="botanicalmachinery.png"
credits=""
authors="MelanX"
description='''

'''

[[dependencies.botanicalmachinery]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.botanicalmachinery]]
    modId="botania"
    mandatory=true
    versionRange="[r1.16,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.botanicalmachinery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="BOTH"
